### ISSUE TITLE
列表的宽高误差会累加，错位很大

### ISSUE THREAD

**Issue by zhuzhutai** [TheMelody/LotteryTrend#1]
怎么解决的

**Comment by TheMelody** [comment]
你好是这样的，14年写这个代码的时候没想到扩展，但是呢，你可以写一个控制类，专门计算单元格的一个类，里面可以传递你要**定制的大小**，当然啦，你的其他几列也要自定义。
只要你的宽高都是定值，应该是没有什么问题的吧？你是重新进行了自定义吗？？？？

**Comment by zhuzhutai** [comment]
说实话大神的代码，对我来说要改动起来挺难的，能否抽空更新一下，这个真的是逻辑和代码的完美结合。。。

**Comment by TheMelody** [comment]
最近确实比较忙，如果实在解决不了，可以进QQ群来直接交流。估计还得忙个1个月差不多。
群:490113234
